x = int(3)
print (x)
y = float(5.6)
print(y)
z = str("Hello 26")
print(z)
a = bytes(1)
print(a)
b = ["a", "b", "c", 1, 2, 3]
print(b[0:4], type(b))
c = tuple("hello")
print(c)
d = set("hi")
print(d)
f = frozenset("bye")
print(f)
t = {"age":27, "name":"Slava"}
print(t.keys(), "===",t.values())
aa = str("hello ")
bb = str("group 26")
cc = aa + bb
print(cc)
print(x, z)
print(x, "+", z)
